# <u><b>Desafio n° 3:</b></u>
<b>Analisis Exploratorio de Dataset clima en el aeropuerto de Barajas-Madrid entre los años 1997 y 2015 </b>

El dataset es originario de https://www.wunderground.com/, pero fue descargado via https://www.kaggle.com/juliansimon/weather_madrid_lemd_1997_2015.csv?select=weather_madrid_LEMD_1997_2015.csv, una comunidad de data scientist.

<b>Grupo 4</b>

<b>Integrantes</b>
<ul>
<li>Cubric, Walter</li>
<li>Flores, Roman</li>
<li>Giusti, Patricio Daniel</li>
<li>Tovar, Alan</li>
<li>Tovar, Franco</li>
</ul>
<b>Imports</b>

In [360]:
#importamos pandas
import pandas as pd
#importamos numpy
import numpy as np
#importamos Expresiones Regulares
import re
#importamos Plotly
import plotly.express as px
#importamos Seaborn
import seaborn as sns
#importamos ip widget
from ipywidgets import interact_manual
#import para traer los ssv
import pyreadstat

In [361]:
#importacion base de datos#
df = pd.read_csv("Data/weather_madrid_LEMD_1997_2015.csv", sep=",")

#print tipo de datos
print(df.dtypes)

#ejemplo primeros tres
df.head()

CET                             object
Max TemperatureC               float64
Mean TemperatureC              float64
Min TemperatureC               float64
Dew PointC                     float64
MeanDew PointC                 float64
Min DewpointC                  float64
Max Humidity                   float64
 Mean Humidity                 float64
 Min Humidity                  float64
 Max Sea Level PressurehPa       int64
 Mean Sea Level PressurehPa      int64
 Min Sea Level PressurehPa       int64
 Max VisibilityKm              float64
 Mean VisibilityKm             float64
 Min VisibilitykM              float64
 Max Wind SpeedKm/h              int64
 Mean Wind SpeedKm/h             int64
 Max Gust SpeedKm/h            float64
Precipitationmm                float64
 CloudCover                    float64
 Events                         object
WindDirDegrees                   int64
dtype: object

,CET,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Max VisibilityKm,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees
0,1997-1-1,7.0,4.0,2.0,5.0,3.0,2.0,100.0,95.0,76.0,...,10.0,9.0,4.0,13,6,NaN,0.0,6.0,NaN,229
1,1997-1-2,7.0,3.0,0.0,6.0,3.0,0.0,100.0,92.0,71.0,...,10.0,9.0,4.0,26,8,47.0,0.0,5.0,Rain,143
2,1997-1-3,5.0,3.0,2.0,5.0,1.0,-1.0,100.0,85.0,70.0,...,10.0,10.0,7.0,27,19,NaN,0.0,6.0,Rain-Snow,256
3,1997-1-4,7.0,3.0,-1.0,-2.0,-3.0,-4.0,86.0,63.0,49.0,...,10.0,10.0,10.0,27,19,40.0,0.0,2.0,NaN,284
4,1997-1-5,2.0,0.0,-1.0,2.0,0.0,-3.0,100.0,95.0,86.0,...,10.0,5.0,1.0,14,6,NaN,0.0,7.0,Snow,2

In [362]:
#revisamos los campos nulos en el dataframe
cant_nulos_por_campo = df.apply(lambda x: x.isnull().sum(), axis=0)
print(cant_nulos_por_campo)

#estimamos cuanto representa esa informacion faltante sobre el total de los datos que tenemos
cant_registros = df.shape[0]
print(cant_registros)

CET                               0
Max TemperatureC                  2
Mean TemperatureC                 3
Min TemperatureC                  2
Dew PointC                        2
MeanDew PointC                    2
Min DewpointC                     2
Max Humidity                      2
 Mean Humidity                    2
 Min Humidity                     2
 Max Sea Level PressurehPa        0
 Mean Sea Level PressurehPa       0
 Min Sea Level PressurehPa        0
 Max VisibilityKm               940
 Mean VisibilityKm              940
 Min VisibilitykM               940
 Max Wind SpeedKm/h               0
 Mean Wind SpeedKm/h              0
 Max Gust SpeedKm/h            3306
Precipitationmm                   0
 CloudCover                    1372
 Events                        5014
WindDirDegrees                    0
dtype: int64
6812

In [363]:
#estimamos cuanto representa esa informacion faltante sobre el total de los datos que tenemos en %

porc_nulos_por_campo = 100 * cant_nulos_por_campo / cant_registros
print(porc_nulos_por_campo)

CET                             0.000000
Max TemperatureC                0.029360
Mean TemperatureC               0.044040
Min TemperatureC                0.029360
Dew PointC                      0.029360
MeanDew PointC                  0.029360
Min DewpointC                   0.029360
Max Humidity                    0.029360
 Mean Humidity                  0.029360
 Min Humidity                   0.029360
 Max Sea Level PressurehPa      0.000000
 Mean Sea Level PressurehPa     0.000000
 Min Sea Level PressurehPa      0.000000
 Max VisibilityKm              13.799178
 Mean VisibilityKm             13.799178
 Min VisibilitykM              13.799178
 Max Wind SpeedKm/h             0.000000
 Mean Wind SpeedKm/h            0.000000
 Max Gust SpeedKm/h            48.532002
Precipitationmm                 0.000000
 CloudCover                    20.140928
 Events                        73.605402
WindDirDegrees                  0.000000
dtype: float64

In [364]:
df.columns

Index(['CET', 'Max TemperatureC', 'Mean TemperatureC', 'Min TemperatureC',
       'Dew PointC', 'MeanDew PointC', 'Min DewpointC', 'Max Humidity',
       ' Mean Humidity', ' Min Humidity', ' Max Sea Level PressurehPa',
       ' Mean Sea Level PressurehPa', ' Min Sea Level PressurehPa',
       ' Max VisibilityKm', ' Mean VisibilityKm', ' Min VisibilitykM',
       ' Max Wind SpeedKm/h', ' Mean Wind SpeedKm/h', ' Max Gust SpeedKm/h',
       'Precipitationmm', ' CloudCover', ' Events', 'WindDirDegrees'],
      dtype='object')

## Definición sobre variable preponderantes para la categorización
Las variables que contamos en la prediccion que queremos realizar son : 
<ul>
    <li><b>Fecha</b>    
        CET = Dia
    <li><b>Temperatura</b><p>Es el indicador de la cantidad de energía calorífica acumulada en el aire
        <ul>
            <li>Max TemperatureC = Max tem
            <li>Mean TemperatureC = Promed temp
            <li>Min TemperatureC = Min Temp
        </ul><p>
    <li><b>Punto de rocío</b><p>es la más alta temperatura a la que empieza a condensarse el vapor de agua contenido en el aire, produciendo rocío, neblina, cualquier tipo de nube o, en caso de que la temperatura sea lo suficientemente baja, escarcha
        <ul>
            <li>Dew PointC = Punto de rocío Max
            <li>MeanDew PointC = Promed Punto rocio
            <li>Min DewpointC = Min Punto rocio
        </ul><p>
    <li><b>Humedad</b> <p>indica la cantidad de vapor de agua que se encuentra presente en el aire.
        <ul>
            <li>Max Humidity = Max humedad
            <li> Mean Humidity = Promed humedad
            <li> Min Humidity = Min humedad
        </ul><p>
    <li><b>Presión atmosférica</b> <p>es el peso de la masa de aire por cada unidad de superficie.
        <ul>
            <li> Max Sea Level PressurehPa = Max humedad
            <li> Mean Sea Level PressurehPa = Promed humedad
            <li> Min Sea Level PressurehPa = Min humedad
        </ul><p>
    <li><b>Visibilidad</b> <p>Se define la “visibilidad meteorológica" como la distancia máxima a la que un objeto negro, de tamaño especificado, puede ser visto y reconocido contra el horizonte por un observador normal, sin que intervenga un procedimiento de iluminación
        <ul>
                <li> Max VisibilityKm = Visibilidad maxima en km
                <li> Mean VisibilityKm = Visibilidad Promed en km
                <li> Min VisibilitykM = Visibilidad minen km
        </ul><p>
    <li><b>Velocidad del viento</b> <p>La velocidad del viento mide la componente horizontal del desplazamiento del aire en un punto y en un instante determinados. 
        <ul>
            <li> Max Wind SpeedKm/h = Viento Max Km/h
            <li> Mean Wind SpeedKm/h = Viento Promed Km/h
            <li> Max Gust SpeedKm/h = Viento min Km/h
        </ul><p>
    <li><b>Precipitación en mm</b><p>La precipitación pluvial se mide en mm, que sería el espesor de la lámina de agua que se formaría, a causa de la precipitación, sobre una superficie plana e impermeable y que equivale a litros de agua por metro cuadrado de terreno (l/m²)
        <ul>
            <li>Precipitationmm = Presipitacion en mm
        </ul><p>
    <li> CloudCover = Covertura de Nubes en escala de 0 a 8
    <li> Events = Clima del dia
    <li>WindDirDegrees = Direccion del viento en grados
    </ul>

In [365]:
df[" Events"].unique()

array([nan, 'Rain', 'Rain-Snow', 'Snow', 'Fog', 'Fog-Rain',
       'Rain-Thunderstorm', 'Thunderstorm', 'Rain-Hail-Thunderstorm',
       'Fog-Thunderstorm', 'Tornado', 'Fog-Rain-Thunderstorm',
       'Fog-Rain-Snow', 'Fog-Snow', 'Rain-Snow-Thunderstorm', 'Rain-Hail'],
      dtype=object)

In [366]:
df.rename(columns={' CloudCover':'CloudCover',' Events':'Events'}, inplace = True)

In [367]:
df.columns

Index(['CET', 'Max TemperatureC', 'Mean TemperatureC', 'Min TemperatureC',
       'Dew PointC', 'MeanDew PointC', 'Min DewpointC', 'Max Humidity',
       ' Mean Humidity', ' Min Humidity', ' Max Sea Level PressurehPa',
       ' Mean Sea Level PressurehPa', ' Min Sea Level PressurehPa',
       ' Max VisibilityKm', ' Mean VisibilityKm', ' Min VisibilitykM',
       ' Max Wind SpeedKm/h', ' Mean Wind SpeedKm/h', ' Max Gust SpeedKm/h',
       'Precipitationmm', 'CloudCover', 'Events', 'WindDirDegrees'],
      dtype='object')

In [368]:
nubes_null = df["CloudCover"].isnull()
nubes_null_y_lluvia = df[nubes_null]["Precipitationmm"].unique()
print("NAN nubes y precipitación únicos" , nubes_null_y_lluvia)
nubes_null_y_clima_unicos = df[nubes_null]["Events"].unique()
print("NAN nubes y clima únicos", nubes_null_y_clima_unicos)
nubes_0 = df["CloudCover"] == 0
nubes_0_y_lluvia_unicos = df[nubes_0]["Precipitationmm"].unique()
print("sin nubes y lluvia únicos",nubes_0_y_lluvia_unicos)
nubes_0_y_lluvia_unicos = df[nubes_0]["Events"].unique()
print("sin nubes y clima únicos",nubes_0_y_lluvia_unicos)
#df.groupby(by=[' Events'],as_index=False)["Precipitationmm"].agg(['count'])
df[nubes_null]["Events"].isnull()

NAN nubes y precipitación únicos [0.]
NAN nubes y clima únicos [nan 'Fog']
sin nubes y lluvia únicos [0.]
sin nubes y clima únicos [nan 'Fog']

40       True
49       True
58       True
59       True
60       True
        ...
6799     True
6802     True
6803     True
6804     True
6805    False
Name: Events, Length: 1372, dtype: bool

In [369]:
#Podemos decir entonces que los que son nullos o tienen nubes 0, son dias soleados, ya que poseen ausencia de precipitaciones. 
#Podemos Remplazar entonces en el DF completo estos datos.  
df_1 = df
df_1["eventos_completo"] = df_1["Events"]

In [370]:
df_1

,CET,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees,eventos_completo
0,1997-1-1,7.0,4.0,2.0,5.0,3.0,2.0,100.0,95.0,76.0,...,9.0,4.0,13,6,NaN,0.00,6.0,NaN,229,NaN
1,1997-1-2,7.0,3.0,0.0,6.0,3.0,0.0,100.0,92.0,71.0,...,9.0,4.0,26,8,47.0,0.00,5.0,Rain,143,Rain
2,1997-1-3,5.0,3.0,2.0,5.0,1.0,-1.0,100.0,85.0,70.0,...,10.0,7.0,27,19,NaN,0.00,6.0,Rain-Snow,256,Rain-Snow
3,1997-1-4,7.0,3.0,-1.0,-2.0,-3.0,-4.0,86.0,63.0,49.0,...,10.0,10.0,27,19,40.0,0.00,2.0,NaN,284,NaN
4,1997-1-5,2.0,0.0,-1.0,2.0,0.0,-3.0,100.0,95.0,86.0,...,5.0,1.0,14,6,NaN,0.00,7.0,Snow,2,Snow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6807,2015-12-27,14.0,7.0,-1.0,6.0,2.0,-2.0,100.0,77.0,30.0,...,14.0,5.0,14,6,NaN,0.00,8.0,Fog,38,Fog
6808,2015-12-28,15.0,8.0,2.0,8.0,4.0,1.0,100.0,78.0,34.0,...,14.0,8.0,27,8,45.0,0.51,7.0,Rain,243,Rain
6809,2015-12-29,11.0,8.0,5.0,9.0,7.0,5.0,100.0,89.0,66.0,...,9.0,0.0,14,8,32.0,2.03,5.0,Fog-Rain,190,Fog-Rain
6810,2015-12-30,9.0,8.0,6.0,7.0,6.0,5.0,93.0,87.0,70.0,...,10.0,6.0,14,5,34.0,0.00,6.0,NaN,256,NaN
6811,2015-12-31,12.0,10.0,7.0,10.0,8.0,7.0,100.0,90.0,70.0,...,8.0,2.0,14,6,NaN,0.25,6.0,Rain,313,Rain

In [371]:
soleado_1 = df_1["CloudCover"].isna()
df_1.loc[soleado_1, "CloudCover"] = 0
df_1["CloudCover"].unique()

array([6., 5., 2., 7., 4., 3., 1., 0., 8.])

In [372]:
soleado_2 = df_1["CloudCover"] == 0
df_1.loc[soleado_2, "eventos_completo"] = "Sunny"

In [373]:
df_1[df_1.eventos_completo=="Sunny"]

,CET,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees,eventos_completo
40,1997-2-10,14.0,7.0,0.0,5.0,3.0,-1.0,100.0,76.0,51.0,...,NaN,NaN,8,3,NaN,0.0,0.0,NaN,284,Sunny
49,1997-2-19,18.0,10.0,2.0,7.0,4.0,2.0,100.0,71.0,40.0,...,NaN,NaN,11,3,NaN,0.0,0.0,NaN,287,Sunny
50,1997-2-20,19.0,10.0,2.0,7.0,5.0,2.0,100.0,72.0,43.0,...,9.0,8.0,8,2,NaN,0.0,0.0,NaN,254,Sunny
58,1997-2-28,21.0,11.0,2.0,5.0,2.0,0.0,93.0,59.0,28.0,...,NaN,NaN,10,3,NaN,0.0,0.0,NaN,347,Sunny
59,1997-3-1,21.0,12.0,4.0,6.0,4.0,3.0,93.0,65.0,33.0,...,NaN,NaN,8,5,NaN,0.0,0.0,NaN,339,Sunny
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6799,2015-12-19,16.0,9.0,2.0,5.0,3.0,1.0,100.0,74.0,31.0,...,10.0,6.0,11,6,NaN,0.0,0.0,NaN,340,Sunny
6802,2015-12-22,16.0,8.0,0.0,6.0,3.0,-1.0,100.0,78.0,36.0,...,12.0,5.0,10,5,NaN,0.0,0.0,NaN,344,Sunny
6803,2015-12-23,15.0,8.0,0.0,5.0,2.0,-1.0,100.0,78.0,35.0,...,12.0,3.0,10,5,23.0,0.0,0.0,NaN,343,Sunny
6804,2015-12-24,11.0,6.0,0.0,5.0,2.0,-1.0,100.0,84.0,54.0,...,8.0,4.0,10,5,NaN,0.0,0.0,NaN,360,Sunny
6805,2015-12-25,14.0,6.0,-2.0,6.0,2.0,-2.0,100.0,83.0,45.0,...,5.0,2.0,14,5,NaN,0.0,0.0,Fog,349,Sunny

In [374]:
df_1["eventos_completo"].unique()

array([nan, 'Rain', 'Rain-Snow', 'Snow', 'Fog', 'Fog-Rain', 'Sunny',
       'Rain-Thunderstorm', 'Thunderstorm', 'Rain-Hail-Thunderstorm',
       'Fog-Thunderstorm', 'Tornado', 'Fog-Rain-Thunderstorm',
       'Fog-Rain-Snow', 'Fog-Snow', 'Rain-Snow-Thunderstorm', 'Rain-Hail'],
      dtype=object)

In [375]:
nubes_1 = df_1["CloudCover"] == 1
nubes_1_y_lluvia_unicos = df_1[nubes_1]["Precipitationmm"].unique()
print("Nubes 1 y lluvia únicos",nubes_1_y_lluvia_unicos)
nubes_1_y_lluvia_unicos = df_1[nubes_1]["Events"].unique()
print("Nubes 1 y clima únicos",nubes_1_y_lluvia_unicos)
#df.groupby(by=[' Events'],as_index=False)["Precipitationmm"].agg(['count'])

Nubes 1 y lluvia únicos [0.   1.02]
Nubes 1 y clima únicos [nan 'Fog' 'Thunderstorm' 'Fog-Thunderstorm' 'Rain-Thunderstorm' 'Rain'
 'Fog-Rain']

In [376]:
#soleado_3 = (df_1['CloudCover'] == 1)&(df_1['Precipitationmm'] == 0)
#df_1.loc[soleado_3, "eventos_completo"] = "Sunny"  
df_1['eventos_completo'] = np.where((df_1['CloudCover'] == 1)
                           & (df_1['Precipitationmm'] == 0) & (df_1['eventos_completo'].isnull()) , #Identifies the case to apply to
                           "Sunny",      #This is the value that is inserted
                           df_1['eventos_completo'])

In [377]:
print("Nubes 1 y clima únicos",nubes_1_y_lluvia_unicos)
df_1[df_1.eventos_completo=="Sunny"]

Nubes 1 y clima únicos [nan 'Fog' 'Thunderstorm' 'Fog-Thunderstorm' 'Rain-Thunderstorm' 'Rain'
 'Fog-Rain']

,CET,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Mean VisibilityKm,Min VisibilitykM,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees,eventos_completo
11,1997-1-12,17.0,10.0,3.0,8.0,6.0,3.0,100.0,84.0,55.0,...,10.0,10.0,14,8,NaN,0.0,1.0,NaN,345,Sunny
34,1997-2-4,12.0,6.0,0.0,3.0,2.0,0.0,100.0,71.0,51.0,...,10.0,10.0,11,5,NaN,0.0,1.0,NaN,239,Sunny
39,1997-2-9,14.0,7.0,-1.0,5.0,2.0,-2.0,93.0,74.0,51.0,...,10.0,10.0,10,3,NaN,0.0,1.0,NaN,359,Sunny
40,1997-2-10,14.0,7.0,0.0,5.0,3.0,-1.0,100.0,76.0,51.0,...,NaN,NaN,8,3,NaN,0.0,0.0,NaN,284,Sunny
47,1997-2-17,15.0,8.0,2.0,5.0,3.0,1.0,100.0,75.0,39.0,...,10.0,10.0,14,5,NaN,0.0,1.0,NaN,190,Sunny
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6799,2015-12-19,16.0,9.0,2.0,5.0,3.0,1.0,100.0,74.0,31.0,...,10.0,6.0,11,6,NaN,0.0,0.0,NaN,340,Sunny
6802,2015-12-22,16.0,8.0,0.0,6.0,3.0,-1.0,100.0,78.0,36.0,...,12.0,5.0,10,5,NaN,0.0,0.0,NaN,344,Sunny
6803,2015-12-23,15.0,8.0,0.0,5.0,2.0,-1.0,100.0,78.0,35.0,...,12.0,3.0,10,5,23.0,0.0,0.0,NaN,343,Sunny
6804,2015-12-24,11.0,6.0,0.0,5.0,2.0,-1.0,100.0,84.0,54.0,...,8.0,4.0,10,5,NaN,0.0,0.0,NaN,360,Sunny
6805,2015-12-25,14.0,6.0,-2.0,6.0,2.0,-2.0,100.0,83.0,45.0,...,5.0,2.0,14,5,NaN,0.0,0.0,Fog,349,Sunny

In [385]:
cant_nulos_por_campo_1 = df_1.apply(lambda x: x.isnull().sum(), axis=0)
print("       nuevo",cant_nulos_por_campo_1)

       nuevo CET                               0
Max TemperatureC                  2
Mean TemperatureC                 3
Min TemperatureC                  2
Dew PointC                        2
MeanDew PointC                    2
Min DewpointC                     2
Max Humidity                      2
 Mean Humidity                    2
 Min Humidity                     2
 Max Sea Level PressurehPa        0
 Mean Sea Level PressurehPa       0
 Min Sea Level PressurehPa        0
 Max VisibilityKm               940
 Mean VisibilityKm              940
 Min VisibilitykM               940
 Max Wind SpeedKm/h               0
 Mean Wind SpeedKm/h              0
 Max Gust SpeedKm/h            3306
Precipitationmm                   0
CloudCover                        0
Events                         5014
WindDirDegrees                    0
eventos_completo               2391
dtype: int64